// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(ToysGamesContext))]
    partial class ToysGamesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.DbModels.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2021, 9, 6, 23, 0, 45, 621, DateTimeKind.Utc).AddTicks(8643),
                            Guid = new Guid("8cf803a9-424b-478c-943b-ee4e9afeebe8"),
                            Name = "Mattel",
                            UpdatedAt = new DateTime(2021, 9, 6, 23, 0, 45, 621, DateTimeKind.Utc).AddTicks(9029)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2021, 9, 6, 23, 0, 45, 621, DateTimeKind.Utc).AddTicks(9707),
                            Guid = new Guid("cd51c2e7-ccc7-405e-929f-d45f5069d4a3"),
                            Name = "Nintendo",
                            UpdatedAt = new DateTime(2021, 9, 6, 23, 0, 45, 621, DateTimeKind.Utc).AddTicks(9710)
                        });
                });

            modelBuilder.Entity("DAL.DbModels.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicThumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            AgeRestriction = 5,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2021, 9, 6, 23, 0, 45, 623, DateTimeKind.Utc).AddTicks(5240),
                            Description = "Introducing Nintendo Switch Lite, a version of the Nintendo Switch system that’s optimized.",
                            Guid = new Guid("6043fee6-c1e6-43a5-8533-7561079619b7"),
                            Name = "Nintendo Switch Lite",
                            Pic = "https://m.media-amazon.com/images/I/71qmF0FHj7L._AC_SL1500_.jpg",
                            PicThumbnail = "https://res.cloudinary.com/walmart-labs/image/upload/w_225,dpr_auto,f_auto,q_auto:good/mg/gm/1p/images/product-images/img_large/00004549688228l.jpg",
                            Price = 8600m,
                            UpdatedAt = new DateTime(2021, 9, 6, 23, 0, 45, 623, DateTimeKind.Utc).AddTicks(5257)
                        });
                });

            modelBuilder.Entity("DAL.DbModels.Product", b =>
                {
                    b.HasOne("DAL.DbModels.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DAL.DbModels.Company", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
